config/routes.rb
Oz::Application.routes.draw do

  get "home/index"
  get "home/indexstu"

  get "home/teacher_form"
  get "home/student_form"
  get "home/teacher_mypage"
  get "home/student_mypage"
  get "home/teacher_create"
  get "home/change_who"
  get "edit/index"
  
  get "top/teacher_top"
  get "teacher_homework/sche"
  
  
  post "home/teacher_create"
  post "home/student_create"

  post "edit/post"
  post "home/create"
  
  get "report/teacher_report"
  

  devise_for :users, path_names: {
    sign_in: "login",
    sign_out: "logout"
  }, skip: :all
  devise_scope :user do
    post "users" => "devise/registrations#create", as: :user_registration

    post "users/password" => "devise/passwords#create", as: :user_password
    get "users/password" => "devise/passwords#new", as: :new_user_password
 
    get "users/login" => "devise/sessions#new", as: :new_user_session
    post "users/login" => "devise/sessions#create", as: :user_session
    get "users/logout" => "devise/sessions#destroy", as: :destroy_user_session
  end

  get "searches/search"
  get "searches/new"
  post "searches/create"
  get "searches/show"
  get "searches/test1"
  get "searches/howto_use"
  post "searches/posttest"
  

  root "home#index"

end

app/models/howto.rb
class Howto < ActiveRecord::Base
end

app/models/money.rb
class Money < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode

end

app/models/poststu.rb
class Poststu < ActiveRecord::Base
end

app/models/purpose.rb
class Purpose < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/sta.rb
class Sta < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/subjectstu.rb
class Subjectstu < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates_presence_of :who
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/week.rb
class Week < ActiveRecord::Base
end

app/models/weekstu.rb
class Weekstu < ActiveRecord::Base
end

app/controllers/top_controller.rb
class TopController < ApplicationController

	def teacher_top
	
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
	def current_post
		@current_post = Post.find_by_id( current_teacher.id )
	end
	
	def post_have?
		current_post != nil
	end
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <meta charset="UTF-8" />

  <%= favicon_link_tag "favicon.ico" %>
  <%= yield :css %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <!--[if lte IE 8]><style>.main{display:none;} .support-note .note-ie{display:block;}</style><![endif]-->
  <%= yield :javascript_header %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
  <% if user_signed_in? %>
  <ul style="opacity: 0;">
    <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
  </ul>
  <% end %>
  <%= yield :javascript_footer %>
</body>
</html>

app/views/shared/_user_nav.html.erb
		<div id="teacher_nav">
            <% if teacher_signed_in? %>
              Logged in as <strong><%= current_teacher.email %></strong>.
              <%= link_to 'Edit profile', edit_teacher_registration_path %> |
              <%= link_to "Logout", destroy_teacher_session_path, method: :delete %>
            <% else %>
              <%= link_to "Sign up", new_teacher_registration_path %> |
              <%= link_to "Login", new_teacher_session_path %>
            <% end %>
          </div>
         